### ISSUE TITLE
Need to pass input arguments to the execution 

### ISSUE THREAD

**Issue by intuwitdev** [googleapis/nodejs-workflows#36]
Hi 

Can we pass the workflow input argument similar to curl based execution ?

curl --request POST --header "Authorization: Bearer "$(gcloud auth application-default print-access-token) \
--header 'Content-Type: application/json' -**-data '{"argument":"{\"firstName\":\"FIRST\",\"lastName\":\"LAST\"}"}'** \
"https://workflowexecutions.googleapis.com/v1/projects/PROJECT_ID/locations/us-central1/workflows/WORKFLOW_NAME/executions"

Please let us know. 

Regards
Saravanan.M

**Comment by krrishdholakia** [comment]
Hi, is there any update on this ??

**Comment by romanlv** [comment]
assigning `execution.argument` worked for me

```
    const data = { val1: "data to pass to workflow" }; 

    const createExecutionRes = await client.createExecution({
      parent: client.workflowPath(projectId, location, name),
      execution: {
        argument: JSON.stringify(data),
      },
    });
```

**Comment by sofisl** [comment]
Hi there! We are migrating this repo to googleapis/google-cloud-node. If this is still an issue for you, please feel free to reopen there. Thank you!
